language: java

jdk:
  - openjdk8

# Whitelist
branches:
  only:
    - master

services:
    # Enable docker service inside travis
    - docker

install:
    # Build the spring boot app and copy the result to the docker folder
    - mvn -U -Dspring.profiles.active=test clean install && cp target/mrnValidation-0.7.0-SNAPSHOT.war docker/mcp-mrn-service-latest.war

before_script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
    # Build the docker image
    - docker build --no-cache -t mcpnet/mrnservice docker
    # Push the image to the repository
    - docker push mcpnet/mrnservice
